name: starter-ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run unit tests
        working-directory: 14-mlops_and_deployment/03-Notebook-to-Package-Testing-and-CI
        run: python -m unittest discover -s tests -v
